language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '12'
deploy:
  skip_cleanup: true
  on:
    repo: iamolegga/nestjs-configure-after
    branch: master
  provider: npm
  email: iamolegga@gmail.com
  api_key: $NPM_TOKEN
script:
  - npm run build
  - npm run test
after_deploy:
  - npm run report
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
