language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '12'
deploy:
  skip_cleanup: true
  on:
    repo: iamolegga/nestjs-configure-after
    branch: master
  provider: npm
  email: iamolegga@gmail.com
  api_key:
    secure: AZ0QBjpP5/l8KCsw+dL+Pj2FRhu1D6HNW/+AGd/nCeGMvRINISak8EkRkJkrsDGS/73UpH3JJ2W53vimp5ibTo/LQPzSyjpzoIhStpmgLsaqncZUVxUpkbBSUcm94B29nkrwDfKY8fNcth9S4d5niXi9jqK3jejOLhAtIkKWqfQUdHXXTS6gXxQ/rwM7tzH9iJR2Z/cDJOlhbb+GfJY4/4UPXE7O2/mwippNivq1uIHCeVHf86rkDRG1bOn6wcLyGibVME+hxkvFSb6pvNk8QsFXcySp0uMYyJBClT8D5Xl8Uoc6PQvlKGajWdGFxj5GoseCLdhQsi2cWMiuzKqA/LPXhQdEtltfs92LFRMy1bc7d9izM6g7qcznWH9213sdgz5CFTR4r7ivcNwUq7SXPRAEc1t7twMwg/+a1HkBRgR2I8+rUo/K7QjPnYIGsXwZMHzQVjhjlncxgozaoDeFQqnlEL6RGyO1Q/CW5qbExW442LEiefXTJaxSVeJZMRQNV4+BP4cB4RyZyZkeLA51/kP0koTOI7xhtV2NztlRrVF0lyWexVOemAC6d8v75rLbfJCzrjLa++YFBiiPHekDkcPNmWu18VBx/lXMDmVn736bF6btKgMh8aPLOBer/1ipnWhI9rp1SL5MYhc8ZarWDUuXWupKBYrR6r1jnNS4res=
script:
  - npm run build
  - npm run test
after_deploy:
  - npm run report
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
