language: node_js
notifications:
  email: false
node_js:
  - '12'
deploy:
  cleanup: false
  edge: true
  on:
    repo: iamolegga/nestjs-configure-after
    tags: true
  provider: npm
  email: iamolegga@gmail.com
  api_token:
    secure: BCMkhYHMjWQ6Xa9Hj6pwc2TAu3Y8lLY/5Idak9QLOJ5ABNXaW6bF2kfwYdJQhX7KkEqUXP3qI+QNZFphMc9OSjbq1BQpv7lalzuvO3IZMqHbx7RXn9odDpw6S6RTFnBBiEAc9n5qyWCsHFXhIRJRBOcERuawvF3fizIdGaQqxd0ZmkLgm3txORzWkiMA/4BoyRIBWUI6DS+IG18jEcfOBMDwtiuVMEXJ03ou8dyGG/5eYbkJl4kMDf3UGPN9zoXIx8yQTloaW7NlCmERtvkPwQyDDSspNpUry1QPDdd6eXRCphFS98fRJ7Bui6gQgGMSPTBANZcMKNP0g9gvr2TZJIXy5dT/s9vc/sfJeXQ8yZ6UUHeQmoSl8JvwLtjwlqHfLXeTCFsFq+j+Xjku4HtBSq4r61xfjmYVI4YruHcCskLW462asLR+67OUwKL7JKg7Agg/w8urZQ0uZRtnupoE8L8xN7B3+MxSqUvw/vAsbi6/uw2ounabDyO+fjwrDaZ4AnY3/yA08W9FKQ7GGnp0OlGtDY43Cn4mfAdPL4i/hNvIXwj8NfbS2LV6YgvgjKjRMfmEP+4ucAmb79oBluxM/bg9DrJ1k1WGBF1lHHXa5ZcJ6m03PxU8qXbPR5R23DTHNxFav2rV+QNf+gcRT4vhBaMqK8itfUY3j7zYC5pEawk=
script:
  - npm run build
  - npm run test
after_deploy:
  - npm run report
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
